// Sample/demo leads spread across all pipeline stages
// Used as fallback when no real data is available

export const MOCK_LEADS = [
  {
    id: 'mock-001',
    created_at: '2026-03-15T10:30:00Z',
    name: 'Margaret Holloway',
    phone: '(860) 554-2317',
    email: 'mholloway@gmail.com',
    address: '142 Elm Ridge Rd, Glastonbury, CT 06033',
    zip_code: '06033',
    what_they_need: 'Full estate cleanout after passing of husband. 4BR colonial, 40+ years of belongings. Some antiques and jewelry noted. Family would like auction items curated.',
    status: 'New Lead',
    notes: 'Spoke with daughter Karen. Very motivated, wants it done within 6 weeks.',
    square_footage: 2800,
    density: 'High',
    item_quality_score: 8,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-002',
    created_at: '2026-03-18T14:00:00Z',
    name: 'Dennis Kowalski',
    phone: '(203) 771-8840',
    email: 'dkowalski@yahoo.com',
    address: '87 Birchwood Dr, Shelton, CT 06484',
    zip_code: '06484',
    what_they_need: 'Moving to assisted living. Needs full cleanout of split-level home. Some furniture could go to auction. Two-car garage packed with tools.',
    status: 'Contacted',
    notes: 'Left voicemail 3/19. Emailed same day. Called back 3/20, very friendly.',
    square_footage: 1950,
    density: 'Medium',
    item_quality_score: 6,
    job_type: 'Both',
    lead_source: 'Senior Living Community',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-003',
    created_at: '2026-03-10T09:15:00Z',
    name: 'Patricia Fenwick',
    phone: '(860) 233-6612',
    email: 'pfenwick@comcast.net',
    address: '311 Prospect Ave, West Hartford, CT 06107',
    zip_code: '06107',
    what_they_need: 'Estate sale + cleanout. Large Tudor with Victorian furniture, silverware, art. Executor of estate, sibling dispute — wants fast professional.',
    status: 'In Talks',
    notes: 'Very motivated. Competing quote from another company. Emphasize our auction network reach.',
    square_footage: 3400,
    density: 'High',
    item_quality_score: 9,
    job_type: 'Both',
    lead_source: 'Realtor',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-004',
    created_at: '2026-03-05T11:00:00Z',
    name: 'Robert Tanner',
    phone: '(203) 445-9201',
    email: 'bob.tanner@gmail.com',
    address: '58 Meadow Lane, Trumbull, CT 06611',
    zip_code: '06611',
    what_they_need: 'Clean out of late mother\'s ranch house. No auction items, just a straight cleanout. Wants it done before listing the house.',
    status: 'Consult Scheduled',
    notes: 'Consult booked for 4/22 at 10am. Realtor referred — Carol Simms from William Raveis.',
    square_footage: 1400,
    density: 'Medium',
    item_quality_score: 4,
    job_type: 'Clean Out',
    lead_source: 'Realtor',
    consult_at: '2026-04-22T10:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-005',
    created_at: '2026-02-28T13:30:00Z',
    name: 'Evelyn Marchetti',
    phone: '(860) 678-4455',
    email: 'evelynm@hotmail.com',
    address: '920 Farmington Ave, Farmington, CT 06032',
    zip_code: '06032',
    what_they_need: 'Downsizing from 4BR to condo. Large collection of antiques and mid-century furniture. Wants auction maximized, rest cleaned out.',
    status: 'Consult Completed',
    notes: 'Walked through 4/10. Very organized. Antiques are legit — Tiffany lamp, Stickley chairs. Deal score should be high.',
    square_footage: 2600,
    density: 'Medium',
    item_quality_score: 9,
    job_type: 'Both',
    lead_source: 'Google',
    consult_at: '2026-04-10T14:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-006',
    created_at: '2026-02-20T10:00:00Z',
    name: 'Gerald Hutchinson',
    phone: '(860) 344-8872',
    email: 'ghutchinson@sbcglobal.net',
    address: '14 Ridgecrest Blvd, Middletown, CT 06457',
    zip_code: '06457',
    what_they_need: 'Clean out garage and basement after estate settlement. No auction. Family keeping furniture. Just hauling old stuff.',
    status: 'Estimate Sent',
    notes: 'Estimate sent 4/14 for $7,200. Waiting on reply. Lower-end job but quick turnaround.',
    square_footage: 1200,
    density: 'Low',
    item_quality_score: 3,
    job_type: 'Clean Out',
    lead_source: 'Google',
    consult_at: '2026-04-12T09:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: 3,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-007',
    created_at: '2026-02-14T16:00:00Z',
    name: 'Dorothy Callahan',
    phone: '(203) 929-7123',
    email: 'doricallahan@gmail.com',
    address: '266 Post Rd, Orange, CT 06477',
    zip_code: '06477',
    what_they_need: 'Full estate — auction + cleanout. Victorian home, 5 bedrooms, heirloom quality furniture and art. One of the kids lives out of state.',
    status: 'Project Accepted',
    notes: 'Signed contract 4/16. Confirmed budget $18,500. Project start TBD pending scheduling.',
    square_footage: 3800,
    density: 'High',
    item_quality_score: 9,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: '2026-04-08T11:00:00Z',
    project_start: '2026-05-05',
    project_end: '2026-05-07',
    crew_size: 5,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [
      { label: 'Contract signed', done: true },
      { label: 'Deposit received', done: true },
      { label: 'Crew assigned', done: false },
      { label: 'Truck reserved', done: false },
    ],
  },
  {
    id: 'mock-008',
    created_at: '2026-02-01T09:00:00Z',
    name: 'Frank Deluca',
    phone: '(860) 242-3390',
    email: 'frankdeluca59@gmail.com',
    address: '77 Cedar Hill Ave, Newington, CT 06111',
    zip_code: '06111',
    what_they_need: 'Clean out of storage unit and small home after dad passed. No auction. Just needs it cleared.',
    status: 'Project Scheduled',
    notes: 'Scheduled for 4/28–4/29. Crew of 3. Confirmed with client.',
    square_footage: 1100,
    density: 'Medium',
    item_quality_score: 3,
    job_type: 'Clean Out',
    lead_source: 'Staff Referral',
    consult_at: '2026-04-18T10:00:00Z',
    project_start: '2026-04-28',
    project_end: '2026-04-29',
    crew_size: 3,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [
      { label: 'Contract signed', done: true },
      { label: 'Deposit received', done: true },
      { label: 'Crew assigned', done: true },
      { label: 'Truck reserved', done: true },
    ],
  },
  {
    id: 'mock-009',
    created_at: '2026-01-20T14:00:00Z',
    name: 'Estate of Harold Briggs',
    phone: '(860) 523-4461',
    email: 'briggsestate@outlook.com',
    address: '39 Sunset Terrace, West Hartford, CT 06119',
    zip_code: '06119',
    what_they_need: 'Large estate auction and full cleanout. Attorney-referred. 3,200 sqft colonial with significant art, jewelry, and antique furniture. High-value items.',
    status: 'Won',
    notes: 'Completed 3/15. Auction grossed $42k. Cleanout wrapped in 2 days. Client very happy. Referred us to neighbor.',
    square_footage: 3200,
    density: 'High',
    item_quality_score: 10,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: '2026-02-28T10:00:00Z',
    project_start: '2026-03-12',
    project_end: '2026-03-15',
    crew_size: 5,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [
      { label: 'Contract signed', done: true },
      { label: 'Deposit received', done: true },
      { label: 'Crew assigned', done: true },
      { label: 'Truck reserved', done: true },
      { label: 'Auction items catalogued', done: true },
      { label: 'Final walkthrough', done: true },
    ],
  },
  {
    id: 'mock-010',
    created_at: '2026-01-10T11:30:00Z',
    name: 'Susan Albright',
    phone: '(203) 386-7744',
    email: 'salbright@gmail.com',
    address: '104 Maple St, Milford, CT 06460',
    zip_code: '06460',
    what_they_need: 'Cleanout of townhouse rental. Tenant left behind a lot. No auction value.',
    status: 'Won',
    notes: 'Completed 2/20. Fast job, 1.5 days. Good client, has 3 more rental properties.',
    square_footage: 1600,
    density: 'Medium',
    item_quality_score: 2,
    job_type: 'Clean Out',
    lead_source: 'Google',
    consult_at: '2026-02-10T14:00:00Z',
    project_start: '2026-02-19',
    project_end: '2026-02-20',
    crew_size: 3,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [
      { label: 'Contract signed', done: true },
      { label: 'Crew assigned', done: true },
      { label: 'Final walkthrough', done: true },
    ],
  },
  {
    id: 'mock-011',
    created_at: '2026-03-22T10:00:00Z',
    name: 'Carl Vickers',
    phone: '(860) 812-5533',
    email: 'cvickers@aol.com',
    address: '550 Wethersfield Ave, Hartford, CT 06114',
    zip_code: '06114',
    what_they_need: 'Auction only — family handling cleanout themselves. Good mid-century furniture and vintage collectibles.',
    status: 'Lost',
    notes: 'Went with Consign It auction house. Price shopped — we were $800 higher. Worth noting for future pricing in 06114 area.',
    square_footage: 1800,
    density: 'Medium',
    item_quality_score: 7,
    job_type: 'Auction',
    lead_source: 'Google',
    consult_at: '2026-04-01T09:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-012',
    created_at: '2026-03-28T15:00:00Z',
    name: 'Janet Ostrowski',
    phone: '(203) 688-4020',
    email: 'j.ostrowski@yahoo.com',
    address: '18 Orchard Hill Rd, Naugatuck, CT 06770',
    zip_code: '06770',
    what_they_need: 'Full estate cleanout. Modest home, mostly donation-level items. No auction interest.',
    status: 'Lost',
    notes: 'Client decided to have family handle it. Not budget-related — just a change of plan.',
    square_footage: 1300,
    density: 'Low',
    item_quality_score: 2,
    job_type: 'Clean Out',
    lead_source: 'Google',
    consult_at: '2026-04-05T13:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-013',
    created_at: '2026-04-01T09:00:00Z',
    name: 'Thomas Reardon',
    phone: '(860) 677-9980',
    email: 'treardon@gmail.com',
    address: '29 Heritage Ln, Simsbury, CT 06070',
    zip_code: '06070',
    what_they_need: 'Estate of late wife. Wants to sell the house but not ready yet. Looking to do a partial cleanout and auction over the summer.',
    status: 'Backlog',
    notes: 'Not ready to move forward until June. Follow up 5/15.',
    square_footage: 2400,
    density: 'Medium',
    item_quality_score: 7,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: '2026-04-14T10:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-014',
    created_at: '2026-04-05T13:00:00Z',
    name: 'Beverly Sampson',
    phone: '(203) 874-2201',
    email: 'bev.sampson@gmail.com',
    address: '73 Soundview Ave, Milford, CT 06460',
    zip_code: '06460',
    what_they_need: 'Cleanout and auction prep for move to Florida. Nice coastal cottage, good quality furniture. Flexible timeline.',
    status: 'Backlog',
    notes: 'Moving date not set yet. She\'ll call us when ready. Very warm lead — referral from Susan Albright.',
    square_footage: 1700,
    density: 'Medium',
    item_quality_score: 8,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-015',
    created_at: '2026-04-08T10:30:00Z',
    name: 'Walter Pemberton',
    phone: '(860) 445-6610',
    email: 'waltpemberton@gmail.com',
    address: '202 Thames St, Groton, CT 06340',
    zip_code: '06340',
    what_they_need: 'Auction of antique tool collection and maritime collectibles. Cleanout of workshop. No regular furniture.',
    status: 'New Lead',
    notes: 'Inbound call. Very specific about the tool collection being high value. Worth a scout visit.',
    square_footage: 900,
    density: 'High',
    item_quality_score: 8,
    job_type: 'Both',
    lead_source: 'Google',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-016',
    created_at: '2026-04-10T08:00:00Z',
    name: 'Helen Kramer',
    phone: '(203) 261-5577',
    email: 'helen.kramer@comcast.net',
    address: '410 Main St S, Woodbury, CT 06798',
    zip_code: '06798',
    what_they_need: 'Full house estate cleanout. Old antique dealer\'s home — decades of inventory mixed in. Potential for significant auction value.',
    status: 'Contacted',
    notes: 'Initial call went great. Sending intro email with service overview. Scheduling consult for next week.',
    square_footage: 2900,
    density: 'High',
    item_quality_score: 9,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-017',
    created_at: '2026-04-12T11:00:00Z',
    name: 'Raymond Costa',
    phone: '(860) 569-8843',
    email: 'rcosta@gmail.com',
    address: '88 Reservoir Rd, Glastonbury, CT 06033',
    zip_code: '06033',
    what_they_need: 'Clean out of basement and detached garage. Some furniture for auction. Quick job, house already listed.',
    status: 'In Talks',
    notes: 'Realtor pushing hard for a start date. Need to match schedule with their open house prep.',
    square_footage: 1500,
    density: 'Medium',
    item_quality_score: 5,
    job_type: 'Both',
    lead_source: 'Realtor',
    consult_at: null,
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
  {
    id: 'mock-018',
    created_at: '2026-04-14T14:30:00Z',
    name: 'Nancy Fitzgerald',
    phone: '(860) 721-3300',
    email: 'nancyfitz@outlook.com',
    address: '35 Buckingham St, Glastonbury, CT 06033',
    zip_code: '06033',
    what_they_need: 'Full estate of grandmother. Large cape cod, well-furnished. Family spread across country. Need professional to handle everything.',
    status: 'Consult Scheduled',
    notes: 'Consult 4/24 at 2pm with daughter Sarah on-site. Attorney contact is James Brophy 860-555-0112.',
    square_footage: 2200,
    density: 'High',
    item_quality_score: 8,
    job_type: 'Both',
    lead_source: 'Referral',
    consult_at: '2026-04-24T14:00:00Z',
    project_start: null,
    project_end: null,
    crew_size: null,
    assigned_to: null,
    organization_id: 'mock-org',
    checklist: [],
  },
]
