-- Seed 18 sample leads for testuser1 and testuser2
-- Run in Supabase SQL Editor

INSERT INTO leads (
  id, created_at, name, phone, email, address, zip_code,
  what_they_need, status, notes, square_footage, density,
  item_quality_score, job_type, lead_source,
  consult_at, project_start, project_end, crew_size,
  organization_id
)
SELECT
  gen_random_uuid(),
  created_at,
  name, phone, email, address, zip_code,
  what_they_need, status, notes, square_footage, density,
  item_quality_score, job_type, lead_source,
  consult_at, project_start, project_end, crew_size,
  org_id
FROM (
  VALUES
  -- testuser1 org
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '35 days', 'Margaret Holloway',       '(860) 554-2317', 'mholloway@gmail.com',       '142 Elm Ridge Rd, Glastonbury, CT 06033',     '06033', 'Full estate cleanout after passing of husband. 4BR colonial, 40+ years of belongings. Some antiques and jewelry noted. Family would like auction items curated.', 'New Lead',          'Spoke with daughter Karen. Very motivated, wants it done within 6 weeks.',                                                 2800, 'High',   8, 'Both',      'Referral',               NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '32 days', 'Dennis Kowalski',         '(203) 771-8840', 'dkowalski@yahoo.com',       '87 Birchwood Dr, Shelton, CT 06484',          '06484', 'Moving to assisted living. Needs full cleanout of split-level home. Some furniture could go to auction. Two-car garage packed with tools.',                       'Contacted',         'Left voicemail. Emailed same day. Called back, very friendly.',                                                            1950, 'Medium', 6, 'Both',      'Senior Living Community', NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '40 days', 'Patricia Fenwick',        '(860) 233-6612', 'pfenwick@comcast.net',      '311 Prospect Ave, West Hartford, CT 06107',   '06107', 'Estate sale + cleanout. Large Tudor with Victorian furniture, silverware, art. Executor of estate, sibling dispute - wants fast professional.',                   'In Talks',          'Very motivated. Competing quote from another company. Emphasize our auction network reach.',                                 3400, 'High',   9, 'Both',      'Realtor',                NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '45 days', 'Robert Tanner',           '(203) 445-9201', 'bob.tanner@gmail.com',      '58 Meadow Lane, Trumbull, CT 06611',          '06611', 'Clean out of late mother''s ranch house. No auction items, just a straight cleanout. Wants it done before listing the house.',                                   'Consult Scheduled', 'Consult booked. Realtor referred - Carol Simms from William Raveis.',                                                       1400, 'Medium', 4, 'Clean Out', 'Realtor',                NOW() + interval '2 days',    NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '50 days', 'Evelyn Marchetti',        '(860) 678-4455', 'evelynm@hotmail.com',       '920 Farmington Ave, Farmington, CT 06032',    '06032', 'Downsizing from 4BR to condo. Large collection of antiques and mid-century furniture. Wants auction maximized, rest cleaned out.',                              'Consult Completed', 'Walked through recently. Very organized. Antiques are legit - Tiffany lamp, Stickley chairs. Deal score should be high.',      2600, 'Medium', 9, 'Both',      'Google',                 NOW() - interval '10 days',   NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '60 days', 'Gerald Hutchinson',       '(860) 344-8872', 'ghutchinson@sbcglobal.net', '14 Ridgecrest Blvd, Middletown, CT 06457',    '06457', 'Clean out garage and basement after estate settlement. No auction. Family keeping furniture. Just hauling old stuff.',                                           'Estimate Sent',     'Estimate sent for $7,200. Waiting on reply. Lower-end job but quick turnaround.',                                            1200, 'Low',    3, 'Clean Out', 'Google',                 NOW() - interval '8 days',    NULL,                          NULL,                          3),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '65 days', 'Dorothy Callahan',        '(203) 929-7123', 'doricallahan@gmail.com',    '266 Post Rd, Orange, CT 06477',               '06477', 'Full estate - auction + cleanout. Victorian home, 5 bedrooms, heirloom quality furniture and art. One of the kids lives out of state.',                         'Project Accepted',  'Signed contract. Confirmed budget $18,500. Project start TBD pending scheduling.',                                           3800, 'High',   9, 'Both',      'Referral',               NOW() - interval '12 days',   NOW() + interval '15 days',    NOW() + interval '17 days',    5),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '79 days', 'Frank Deluca',            '(860) 242-3390', 'frankdeluca59@gmail.com',   '77 Cedar Hill Ave, Newington, CT 06111',      '06111', 'Clean out of storage unit and small home after dad passed. No auction. Just needs it cleared.',                                                                   'Project Scheduled', 'Scheduled for next week. Crew of 3. Confirmed with client.',                                                                1100, 'Medium', 3, 'Clean Out', 'Staff Referral',          NOW() - interval '2 days',    NOW() + interval '8 days',     NOW() + interval '9 days',     3),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '90 days', 'Estate of Harold Briggs', '(860) 523-4461', 'briggsestate@outlook.com',  '39 Sunset Terrace, West Hartford, CT 06119',  '06119', 'Large estate auction and full cleanout. Attorney-referred. 3,200 sqft colonial with significant art, jewelry, and antique furniture. High-value items.',         'Won',               'Completed recently. Auction grossed $42k. Cleanout wrapped in 2 days. Client very happy. Referred us to neighbor.',           3200, 'High',  10, 'Both',      'Referral',               NOW() - interval '51 days',   NOW() - interval '39 days',    NOW() - interval '36 days',    5),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '100 days','Susan Albright',          '(203) 386-7744', 'salbright@gmail.com',       '104 Maple St, Milford, CT 06460',             '06460', 'Cleanout of townhouse rental. Tenant left behind a lot. No auction value.',                                                                                       'Won',               'Completed. Fast job, 1.5 days. Good client, has 3 more rental properties.',                                                  1600, 'Medium', 2, 'Clean Out', 'Google',                 NOW() - interval '69 days',   NOW() - interval '61 days',    NOW() - interval '60 days',    3),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '29 days', 'Carl Vickers',            '(860) 812-5533', 'cvickers@aol.com',          '550 Wethersfield Ave, Hartford, CT 06114',    '06114', 'Auction only - family handling cleanout themselves. Good mid-century furniture and vintage collectibles.',                                                        'Lost',              'Went with Consign It auction house. Price shopped - we were $800 higher. Worth noting for future pricing in 06114 area.',    1800, 'Medium', 7, 'Auction',   'Google',                 NOW() - interval '19 days',   NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '23 days', 'Janet Ostrowski',         '(203) 688-4020', 'j.ostrowski@yahoo.com',     '18 Orchard Hill Rd, Naugatuck, CT 06770',     '06770', 'Full estate cleanout. Modest home, mostly donation-level items. No auction interest.',                                                                           'Lost',              'Client decided to have family handle it. Not budget-related - just a change of plan.',                                        1300, 'Low',    2, 'Clean Out', 'Google',                 NOW() - interval '15 days',   NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '19 days', 'Thomas Reardon',          '(860) 677-9980', 'treardon@gmail.com',        '29 Heritage Ln, Simsbury, CT 06070',          '06070', 'Estate of late wife. Wants to sell the house but not ready yet. Looking to do a partial cleanout and auction over the summer.',                                  'Backlog',           'Not ready to move forward for a couple months. Follow up later.',                                                            2400, 'Medium', 7, 'Both',      'Referral',               NOW() - interval '6 days',    NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '15 days', 'Beverly Sampson',         '(203) 874-2201', 'bev.sampson@gmail.com',     '73 Soundview Ave, Milford, CT 06460',         '06460', 'Cleanout and auction prep for move to Florida. Nice coastal cottage, good quality furniture. Flexible timeline.',                                               'Backlog',           'Moving date not set yet. She''ll call us when ready. Very warm lead - referral from Susan Albright.',                         1700, 'Medium', 8, 'Both',      'Referral',               NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '12 days', 'Walter Pemberton',        '(860) 445-6610', 'waltpemberton@gmail.com',   '202 Thames St, Groton, CT 06340',             '06340', 'Auction of antique tool collection and maritime collectibles. Cleanout of workshop. No regular furniture.',                                                        'New Lead',          'Inbound call. Very specific about the tool collection being high value. Worth a scout visit.',                                  900,  'High',   8, 'Both',      'Google',                 NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '10 days', 'Helen Kramer',            '(203) 261-5577', 'helen.kramer@comcast.net',  '410 Main St S, Woodbury, CT 06798',           '06798', 'Full house estate cleanout. Old antique dealer''s home - decades of inventory mixed in. Potential for significant auction value.',                              'Contacted',         'Initial call went great. Sending intro email with service overview. Scheduling consult for next week.',                       2900, 'High',   9, 'Both',      'Referral',               NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '8 days',  'Raymond Costa',           '(860) 569-8843', 'rcosta@gmail.com',          '88 Reservoir Rd, Glastonbury, CT 06033',      '06033', 'Clean out of basement and detached garage. Some furniture for auction. Quick job, house already listed.',                                                         'In Talks',          'Realtor pushing hard for a start date. Need to match schedule with their open house prep.',                                    1500, 'Medium', 5, 'Both',      'Realtor',                NULL,                         NULL,                          NULL,                          NULL),
  ('b025be28-a9a1-4e72-b58b-c5186b613e3e'::uuid, NOW() - interval '6 days',  'Nancy Fitzgerald',        '(860) 721-3300', 'nancyfitz@outlook.com',     '35 Buckingham St, Glastonbury, CT 06033',     '06033', 'Full estate of grandmother. Large cape cod, well-furnished. Family spread across country. Need professional to handle everything.',                             'Consult Scheduled', 'Consult scheduled with daughter Sarah on-site. Attorney contact is James Brophy 860-555-0112.',                               2200, 'High',   8, 'Both',      'Referral',               NOW() + interval '4 days',    NULL,                          NULL,                          NULL),
  -- testuser2 org
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '35 days', 'Margaret Holloway',       '(860) 554-2317', 'mholloway@gmail.com',       '142 Elm Ridge Rd, Glastonbury, CT 06033',     '06033', 'Full estate cleanout after passing of husband. 4BR colonial, 40+ years of belongings. Some antiques and jewelry noted. Family would like auction items curated.', 'New Lead',          'Spoke with daughter Karen. Very motivated, wants it done within 6 weeks.',                                                 2800, 'High',   8, 'Both',      'Referral',               NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '32 days', 'Dennis Kowalski',         '(203) 771-8840', 'dkowalski@yahoo.com',       '87 Birchwood Dr, Shelton, CT 06484',          '06484', 'Moving to assisted living. Needs full cleanout of split-level home. Some furniture could go to auction. Two-car garage packed with tools.',                       'Contacted',         'Left voicemail. Emailed same day. Called back, very friendly.',                                                            1950, 'Medium', 6, 'Both',      'Senior Living Community', NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '40 days', 'Patricia Fenwick',        '(860) 233-6612', 'pfenwick@comcast.net',      '311 Prospect Ave, West Hartford, CT 06107',   '06107', 'Estate sale + cleanout. Large Tudor with Victorian furniture, silverware, art. Executor of estate, sibling dispute - wants fast professional.',                   'In Talks',          'Very motivated. Competing quote from another company. Emphasize our auction network reach.',                                 3400, 'High',   9, 'Both',      'Realtor',                NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '45 days', 'Robert Tanner',           '(203) 445-9201', 'bob.tanner@gmail.com',      '58 Meadow Lane, Trumbull, CT 06611',          '06611', 'Clean out of late mother''s ranch house. No auction items, just a straight cleanout. Wants it done before listing the house.',                                   'Consult Scheduled', 'Consult booked. Realtor referred - Carol Simms from William Raveis.',                                                       1400, 'Medium', 4, 'Clean Out', 'Realtor',                NOW() + interval '2 days',    NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '50 days', 'Evelyn Marchetti',        '(860) 678-4455', 'evelynm@hotmail.com',       '920 Farmington Ave, Farmington, CT 06032',    '06032', 'Downsizing from 4BR to condo. Large collection of antiques and mid-century furniture. Wants auction maximized, rest cleaned out.',                              'Consult Completed', 'Walked through recently. Very organized. Antiques are legit - Tiffany lamp, Stickley chairs. Deal score should be high.',      2600, 'Medium', 9, 'Both',      'Google',                 NOW() - interval '10 days',   NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '60 days', 'Gerald Hutchinson',       '(860) 344-8872', 'ghutchinson@sbcglobal.net', '14 Ridgecrest Blvd, Middletown, CT 06457',    '06457', 'Clean out garage and basement after estate settlement. No auction. Family keeping furniture. Just hauling old stuff.',                                           'Estimate Sent',     'Estimate sent for $7,200. Waiting on reply. Lower-end job but quick turnaround.',                                            1200, 'Low',    3, 'Clean Out', 'Google',                 NOW() - interval '8 days',    NULL,                          NULL,                          3),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '65 days', 'Dorothy Callahan',        '(203) 929-7123', 'doricallahan@gmail.com',    '266 Post Rd, Orange, CT 06477',               '06477', 'Full estate - auction + cleanout. Victorian home, 5 bedrooms, heirloom quality furniture and art. One of the kids lives out of state.',                         'Project Accepted',  'Signed contract. Confirmed budget $18,500. Project start TBD pending scheduling.',                                           3800, 'High',   9, 'Both',      'Referral',               NOW() - interval '12 days',   NOW() + interval '15 days',    NOW() + interval '17 days',    5),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '79 days', 'Frank Deluca',            '(860) 242-3390', 'frankdeluca59@gmail.com',   '77 Cedar Hill Ave, Newington, CT 06111',      '06111', 'Clean out of storage unit and small home after dad passed. No auction. Just needs it cleared.',                                                                   'Project Scheduled', 'Scheduled for next week. Crew of 3. Confirmed with client.',                                                                1100, 'Medium', 3, 'Clean Out', 'Staff Referral',          NOW() - interval '2 days',    NOW() + interval '8 days',     NOW() + interval '9 days',     3),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '90 days', 'Estate of Harold Briggs', '(860) 523-4461', 'briggsestate@outlook.com',  '39 Sunset Terrace, West Hartford, CT 06119',  '06119', 'Large estate auction and full cleanout. Attorney-referred. 3,200 sqft colonial with significant art, jewelry, and antique furniture. High-value items.',         'Won',               'Completed recently. Auction grossed $42k. Cleanout wrapped in 2 days. Client very happy. Referred us to neighbor.',           3200, 'High',  10, 'Both',      'Referral',               NOW() - interval '51 days',   NOW() - interval '39 days',    NOW() - interval '36 days',    5),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '100 days','Susan Albright',          '(203) 386-7744', 'salbright@gmail.com',       '104 Maple St, Milford, CT 06460',             '06460', 'Cleanout of townhouse rental. Tenant left behind a lot. No auction value.',                                                                                       'Won',               'Completed. Fast job, 1.5 days. Good client, has 3 more rental properties.',                                                  1600, 'Medium', 2, 'Clean Out', 'Google',                 NOW() - interval '69 days',   NOW() - interval '61 days',    NOW() - interval '60 days',    3),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '29 days', 'Carl Vickers',            '(860) 812-5533', 'cvickers@aol.com',          '550 Wethersfield Ave, Hartford, CT 06114',    '06114', 'Auction only - family handling cleanout themselves. Good mid-century furniture and vintage collectibles.',                                                        'Lost',              'Went with Consign It auction house. Price shopped - we were $800 higher. Worth noting for future pricing in 06114 area.',    1800, 'Medium', 7, 'Auction',   'Google',                 NOW() - interval '19 days',   NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '23 days', 'Janet Ostrowski',         '(203) 688-4020', 'j.ostrowski@yahoo.com',     '18 Orchard Hill Rd, Naugatuck, CT 06770',     '06770', 'Full estate cleanout. Modest home, mostly donation-level items. No auction interest.',                                                                           'Lost',              'Client decided to have family handle it. Not budget-related - just a change of plan.',                                        1300, 'Low',    2, 'Clean Out', 'Google',                 NOW() - interval '15 days',   NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '19 days', 'Thomas Reardon',          '(860) 677-9980', 'treardon@gmail.com',        '29 Heritage Ln, Simsbury, CT 06070',          '06070', 'Estate of late wife. Wants to sell the house but not ready yet. Looking to do a partial cleanout and auction over the summer.',                                  'Backlog',           'Not ready to move forward for a couple months. Follow up later.',                                                            2400, 'Medium', 7, 'Both',      'Referral',               NOW() - interval '6 days',    NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '15 days', 'Beverly Sampson',         '(203) 874-2201', 'bev.sampson@gmail.com',     '73 Soundview Ave, Milford, CT 06460',         '06460', 'Cleanout and auction prep for move to Florida. Nice coastal cottage, good quality furniture. Flexible timeline.',                                               'Backlog',           'Moving date not set yet. She''ll call us when ready. Very warm lead - referral from Susan Albright.',                         1700, 'Medium', 8, 'Both',      'Referral',               NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '12 days', 'Walter Pemberton',        '(860) 445-6610', 'waltpemberton@gmail.com',   '202 Thames St, Groton, CT 06340',             '06340', 'Auction of antique tool collection and maritime collectibles. Cleanout of workshop. No regular furniture.',                                                        'New Lead',          'Inbound call. Very specific about the tool collection being high value. Worth a scout visit.',                                  900,  'High',   8, 'Both',      'Google',                 NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '10 days', 'Helen Kramer',            '(203) 261-5577', 'helen.kramer@comcast.net',  '410 Main St S, Woodbury, CT 06798',           '06798', 'Full house estate cleanout. Old antique dealer''s home - decades of inventory mixed in. Potential for significant auction value.',                              'Contacted',         'Initial call went great. Sending intro email with service overview. Scheduling consult for next week.',                       2900, 'High',   9, 'Both',      'Referral',               NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '8 days',  'Raymond Costa',           '(860) 569-8843', 'rcosta@gmail.com',          '88 Reservoir Rd, Glastonbury, CT 06033',      '06033', 'Clean out of basement and detached garage. Some furniture for auction. Quick job, house already listed.',                                                         'In Talks',          'Realtor pushing hard for a start date. Need to match schedule with their open house prep.',                                    1500, 'Medium', 5, 'Both',      'Realtor',                NULL,                         NULL,                          NULL,                          NULL),
  ('0a59d1ab-21db-4bdf-a1a0-f994b079a7c8'::uuid, NOW() - interval '6 days',  'Nancy Fitzgerald',        '(860) 721-3300', 'nancyfitz@outlook.com',     '35 Buckingham St, Glastonbury, CT 06033',     '06033', 'Full estate of grandmother. Large cape cod, well-furnished. Family spread across country. Need professional to handle everything.',                             'Consult Scheduled', 'Consult scheduled with daughter Sarah on-site. Attorney contact is James Brophy 860-555-0112.',                               2200, 'High',   8, 'Both',      'Referral',               NOW() + interval '4 days',    NULL,                          NULL,                          NULL)
) AS t(org_id, created_at, name, phone, email, address, zip_code, what_they_need, status, notes,
        square_footage, density, item_quality_score, job_type, lead_source,
        consult_at, project_start, project_end, crew_size);
